names:
- mikado
- kinder_pingui
- kinder_country
- kinder_tronky
- tic_tac
- sucette
- capsule
- pepito
- bouteille_plastique
- canette
nc: 10
test: ./datasets/structured/images/test
train: ./datasets/structured/images/train
val: ./datasets/structured/images/val
